// F&D — dados dos prompts (fonte única de verdade do conteúdo).
// Módulo PURO (sem efeitos) partilhado por:
//   - server/prisma/seed.js        (semeia a BD)
//   - server/src/repo.js           (repositório em memória, pré-BD)
// Assim o seed e o jogo nunca divergem. Cada prompt: [texto, intensidade].

export const GAME_TYPES = [
  {
    key: 'boca_calada',
    label: 'Boca Calada',
    prompts: [
      ['Fica sério durante 60s enquanto o grupo tenta fazer-te rir.', 'leve'],
      ['Não podes falar até ser a tua próxima vez. Falas = perdes vida.', 'leve'],
      ['Aguenta 30s a olhar nos olhos do jogador à tua direita sem rir.', 'leve'],
      ['Só podes responder por gestos até ao fim da ronda.', 'leve'],
      ['Mantém a cara séria enquanto o grupo conta a piada mais má que souber.', 'leve'],
      ['Fica calado e imita a expressão de quem estiver a falar contigo.', 'leve'],
      ['Aguenta sem sorrir enquanto todos dizem o teu nome em tom ridículo.', 'leve'],
      ['Não podes dizer "sim" nem "não" durante duas rondas.', 'leve'],
      ['Fica sério enquanto o grupo faz sons de animais à tua volta.', 'leve'],
      ['Mantém a boca fechada durante 45s enquanto te fazem cócegas com o olhar.', 'leve'],
      ['Aguenta sem rir enquanto alguém te elogia exageradamente.', 'leve'],
      ['Fica sério enquanto o grupo reencena o teu momento mais embaraçoso.', 'picante'],
      ['Não podes rir enquanto contam a história mais constrangedora sobre ti.', 'picante'],
      ['Aguenta sério enquanto o teu crush do grupo (se houver) te faz olhinhos.', 'picante'],
      ['Fica calado enquanto o grupo vota se és bom ou mau a beijar.', 'picante'],
      ['Mantém a pose enquanto alguém imita como ficas depois de uns copos.', 'picante'],
      ['Não podes reagir enquanto leem em voz alta a tua última mensagem enviada.', 'picante'],
      ['Fica sério enquanto o grupo descreve o teu tipo ideal.', 'picante'],
      ['Aguenta sem rir enquanto fazem uma imitação tua a paquerar.', 'picante'],
      ['Não podes falar enquanto respondes por gestos "o que farias numa primeira noite".', 'picante'],
      ['Mantém a cara séria enquanto o grupo adivinha o teu segredo mais picante.', 'picante'],
      ['Fica calado enquanto dois jogadores discutem quem gosta mais de ti.', 'picante'],
      ['Mantém a cara séria enquanto o grupo diz em voz alta o teu "tipo" na cama.', 'hardcore'],
      ['Aguenta sem reagir enquanto leem a tua conversa mais picante do telemóvel.', 'hardcore'],
      ['Fica sério enquanto o grupo vota quem levarias para casa esta noite.', 'hardcore'],
      ['Não podes rir enquanto alguém recria o teu pior fora da noite.', 'hardcore'],
      ['Mantém a pose enquanto descrevem o teu momento mais +18 conhecido.', 'hardcore'],
      ['Fica calado enquanto o grupo adivinha a tua fantasia mais secreta.', 'hardcore'],
      ['Fica calado enquanto cada um diz, à vez, uma verdade dura sobre ti.', 'caos'],
      ['Mantém a cara séria enquanto o grupo revela o que já disseram sobre ti nas costas.', 'caos'],
      ['Aguenta sem reagir enquanto dizem quem desta mesa aturam menos — e porquê.', 'caos'],
      ['Não podes falar enquanto expõem a tua maior falha de caráter (segundo o grupo).', 'caos'],
      ['Fica sério enquanto contam a última vez que ficaste mal na fita à frente deles.', 'caos'],
      ['Mantém a pose enquanto o grupo decide se és de confiança ou não.', 'caos'],
    ],
  },
  {
    key: 'desafio',
    label: 'Desafio',
    prompts: [
      ['Faz a tua melhor imitação de outro jogador; se ninguém adivinhar, bebes.', 'leve'],
      ['Fala com sotaque estrangeiro até à tua próxima vez.', 'leve'],
      ['Liga a um contacto aleatório e canta-lhe os parabéns.', 'leve'],
      ['Dança 20 segundos sem música.', 'leve'],
      ['Deixa o jogador à tua esquerda publicar um emoji no teu status.', 'leve'],
      ['Faz 10 flexões ou bebes dois copos.', 'leve'],
      ['Fala só a rimar durante a próxima ronda.', 'leve'],
      ['Imita um animal até alguém adivinhar qual é.', 'leve'],
      ['Deixa o grupo escolher-te uma nova alcunha para o resto do jogo.', 'leve'],
      ['Conta uma anedota; se ninguém rir, bebes.', 'leve'],
      ['Faz uma pose de ginásio e mantém-na 30s.', 'leve'],
      ['Envia "estava só a pensar em ti 😊" à terceira conversa do teu WhatsApp.', 'picante'],
      ['Mostra a última foto da tua galeria (sem escolher).', 'picante'],
      ['Deixa o grupo ler a tua última mensagem enviada em voz alta.', 'picante'],
      ['Descreve o teu pior encontro em três frases.', 'picante'],
      ['Deixa o jogador à tua direita escrever um story teu por 15s.', 'picante'],
      ['Troca uma peça de roupa com o jogador ao teu lado.', 'picante'],
      ['Faz uma serenata improvisada a quem o grupo escolher.', 'picante'],
      ['Confessa qual foi a maior mentira que disseste neste grupo.', 'picante'],
      ['Deixa o grupo ver quantas conversas tens fixadas — sem abrir.', 'picante'],
      ['Recria o teu melhor movimento de dança "de fim de noite".', 'picante'],
      ['Manda uma nota de voz a cantar para o último contacto com quem falaste.', 'picante'],
      ['Liga a um ex e diz "ainda penso em ti" durante 10s — ou bebes 3.', 'hardcore'],
      ['Mostra a última foto que enviaste a alguém depois da meia-noite.', 'hardcore'],
      ['Deixa o grupo ler a tua conversa mais recente, sem apagar nada.', 'hardcore'],
      ['Diz o nome de alguém no grupo com quem terias uma aventura — ou bebes 4.', 'hardcore'],
      ['Descreve o teu momento mais +18 em três palavras.', 'hardcore'],
      ['Deixa o jogador à tua direita publicar um story teu à escolha dele.', 'hardcore'],
      ['Qual foi a maior mentira que contaste a alguém desta mesa? Confessa ou bebes 3.', 'caos'],
      ['Diz qual das pessoas aqui já te irritou a sério — e porquê. Ou bebes 4.', 'caos'],
      ['Confessa a última vez que falaste de alguém desta mesa nas costas.', 'caos'],
      ['Ordena as pessoas da mesa de quem confias mais para quem confias menos, em voz alta.', 'caos'],
      ['Diz a coisa que mudarias em cada pessoa à tua esquerda e à tua direita.', 'caos'],
      ['Revela um crush passado ou presente por alguém desta mesa — ou bebes 5.', 'caos'],
    ],
  },
  {
    key: 'intrigas',
    label: 'Intrigas',
    prompts: [
      ['Quem é mais capaz de adormecer numa festa? O grupo vota.', 'leve'],
      ['Quem chega sempre atrasado? Votem.', 'leve'],
      ['Quem tem o pior gosto musical? Votação.', 'leve'],
      ['Quem é mais provável de perder o telemóvel esta noite?', 'leve'],
      ['Quem fala mais alto quando bebe?', 'leve'],
      ['Quem seria o pior a guardar um segredo?', 'leve'],
      ['Quem gasta mais tempo ao espelho?', 'leve'],
      ['Quem é mais capaz de comer o que sobra no prato dos outros?', 'leve'],
      ['Quem seria o primeiro a fugir num filme de terror?', 'leve'],
      ['Quem tem sempre a desculpa mais criativa para faltar?', 'leve'],
      ['Quem é o mais dramático do grupo?', 'leve'],
      ['Quem é mais provável de mandar mensagem ao ex a meio da noite?', 'picante'],
      ['Quem já teve a maior queda por alguém deste grupo?', 'picante'],
      ['Quem é mais capaz de beijar um desconhecido numa saída?', 'picante'],
      ['Quem tem mais probabilidade de ter um crush secreto agora mesmo?', 'picante'],
      ['Quem seria o mais atrevido num jogo de verdade ou consequência?', 'picante'],
      ['Quem já flirtou para não pagar a conta?', 'picante'],
      ['Quem é mais provável de se apaixonar em férias?', 'picante'],
      ['Quem tem o histórico de encontros mais caótico?', 'picante'],
      ['Quem seria o primeiro a dizer "eu amo-te" cedo demais?', 'picante'],
      ['Quem é mais capaz de dar o número falso a alguém?', 'picante'],
      ['Quem tem a maior probabilidade de acabar a noite a dançar em cima da mesa?', 'picante'],
      ['Quem do grupo já teve a noite mais louca? Votem.', 'hardcore'],
      ['Quem é mais capaz de dar uns beijos a um desconhecido hoje?', 'hardcore'],
      ['Quem tem o histórico mais caótico de mensagens a horas tardias?', 'hardcore'],
      ['Quem seria o mais atrevido debaixo dos lençóis?', 'hardcore'],
      ['Quem já ficou (ou quase) com alguém deste grupo?', 'hardcore'],
      ['Quem é mais provável de acabar a noite acompanhado/a?', 'hardcore'],
      ['Quem nesta mesa é mais falso? O grupo decide.', 'caos'],
      ['Quem já falou mal de mais gente aqui presente?', 'caos'],
      ['Em quem confias menos para guardar um segredo teu?', 'caos'],
      ['Quem é mais provável de andar a namoriscar alguém do grupo às escondidas?', 'caos'],
      ['Quem seria o primeiro a trair o grupo por interesse próprio?', 'caos'],
      ['Quem aqui já gostou de alguém do grupo e nunca admitiu?', 'caos'],
    ],
  },
  {
    key: 'segredos',
    label: 'Segredos Anónimos',
    prompts: [
      ['Submete um segredo sobre a tua infância. O grupo adivinha de quem é.', 'leve'],
      ['Confessa anonimamente um medo estranho que tenhas.', 'leve'],
      ['Partilha a coisa mais infantil que ainda fazes.', 'leve'],
      ['Escreve um talento escondido que ninguém aqui conhece.', 'leve'],
      ['Confessa um hábito esquisito que tens quando estás sozinho/a.', 'leve'],
      ['Partilha a compra mais inútil que já fizeste.', 'leve'],
      ['Escreve algo por que já choraste a ver um filme.', 'leve'],
      ['Confessa uma mentira inofensiva que dizes com frequência.', 'leve'],
      ['Partilha o prato que finges gostar mas odeias.', 'leve'],
      ['Escreve a coisa mais embaraçosa que tens no histórico de pesquisa.', 'leve'],
      ['Confessa uma manha que usas para faltar a compromissos.', 'leve'],
      ['Partilha um segredo sobre a tua vida amorosa. O grupo adivinha de quem é.', 'picante'],
      ['Confessa anonimamente o teu maior arrependimento romântico.', 'picante'],
      ['Escreve o sítio mais inusitado onde já deste um beijo.', 'picante'],
      ['Partilha algo que nunca contaste a ninguém deste grupo.', 'picante'],
      ['Confessa se já tiveste um crush em alguém presente (sem dizer quem).', 'picante'],
      ['Escreve a mensagem mais atrevida que já enviaste.', 'picante'],
      ['Partilha o encontro mais louco que já tiveste.', 'picante'],
      ['Confessa uma paixoneta secreta por alguém famoso improvável.', 'picante'],
      ['Escreve algo de que te arrependes de ter feito numa festa.', 'picante'],
      ['Partilha a desculpa mais dramática que já deste para acabar um encontro.', 'picante'],
      ['Confessa o segredo que levarias para o túmulo... até agora.', 'picante'],
      ['Confessa anonimamente a tua fantasia mais inconfessável.', 'hardcore'],
      ['Escreve o sítio mais arriscado onde já foste longe demais.', 'hardcore'],
      ['Partilha o segredo +18 que nunca contaste a ninguém.', 'hardcore'],
      ['Confessa se já tiveste algo com alguém presente — sem dizer quem.', 'hardcore'],
      ['Escreve a coisa mais atrevida que já fizeste sóbrio/a.', 'hardcore'],
      ['Partilha o teu maior arrependimento de uma noite de festa.', 'hardcore'],
      ['Confessa (anónimo) a maior mentira que já disseste a alguém desta mesa.', 'caos'],
      ['Escreve o que realmente sentiste da última vez que discutiste com alguém aqui.', 'caos'],
      ['Confessa se já perdeste o respeito por alguém do grupo — sem dizer quem.', 'caos'],
      ['Partilha a coisa mais dramática que já fizeste por causa de alguém desta mesa.', 'caos'],
      ['Escreve um arrependimento que tens com alguém presente.', 'caos'],
      ['Confessa se alguma vez fingiste gostar de alguém do grupo.', 'caos'],
    ],
  },
  {
    // Piramide (Desconfia) — jogo dirigido por MECÂNICA, não por prompts de texto.
    // As cartas e a pirâmide são geradas no motor (game.js); não há banco de prompts.
    // Fica em GAME_TYPES só para entrar na roda (repo.getGameTypes) e no seed (0 prompts).
    key: 'piramide',
    label: 'Piramide',
    prompts: [],
  },
  {
    // Jogo do Vasco (Impostor) — também dirigido por MECÂNICA. O conteúdo são
    // QUADROS de palavras (VASCO_BOARDS abaixo), não prompts de texto. Fica aqui
    // só para entrar na roda e no seed (0 prompts).
    key: 'vasco',
    label: 'Jogo do Vasco',
    prompts: [],
  },
];

// Quadros do Jogo do Vasco: cada quadro tem um tema e 9 palavras (grelha 3×3).
// O grupo recebe uma das palavras como secreta; o(s) Vasco(s) não a sabem e têm
// de a adivinhar pelas pistas. Palavras neutras (sem intensidade).
export const VASCO_BOARDS = [
  { theme: 'Praia', words: ['Mar', 'Areia', 'Sol', 'Toalha', 'Chapéu', 'Onda', 'Barco', 'Concha', 'Bronzeado'] },
  { theme: 'Cozinha', words: ['Faca', 'Panela', 'Forno', 'Sal', 'Colher', 'Prato', 'Fogão', 'Azeite', 'Frigorífico'] },
  { theme: 'Festa', words: ['Música', 'Balões', 'Bolo', 'Copos', 'Dança', 'Prenda', 'Convite', 'Vela', 'Confetti'] },
  { theme: 'Futebol', words: ['Golo', 'Árbitro', 'Bola', 'Relvado', 'Adepto', 'Penálti', 'Camisola', 'Estádio', 'Baliza'] },
  { theme: 'Cinema', words: ['Pipocas', 'Ecrã', 'Bilhete', 'Realizador', 'Trailer', 'Cadeira', 'Legenda', 'Estreia', 'Ator'] },
  { theme: 'Viagem', words: ['Mala', 'Avião', 'Passaporte', 'Hotel', 'Mapa', 'Comboio', 'Roteiro', 'Fronteira', 'Câmara'] },
  { theme: 'Escola', words: ['Caderno', 'Professor', 'Exame', 'Recreio', 'Mochila', 'Quadro', 'Nota', 'Caneta', 'Intervalo'] },
  { theme: 'Animais', words: ['Cão', 'Gato', 'Leão', 'Elefante', 'Cobra', 'Águia', 'Golfinho', 'Coelho', 'Tubarão'] },
  { theme: 'Corpo', words: ['Cabeça', 'Mão', 'Joelho', 'Cotovelo', 'Ombro', 'Nariz', 'Tornozelo', 'Dedo', 'Costas'] },
  { theme: 'Natal', words: ['Presente', 'Pinheiro', 'Presépio', 'Rena', 'Neve', 'Bacalhau', 'Pai Natal', 'Estrela', 'Meia'] },
  { theme: 'Música', words: ['Guitarra', 'Bateria', 'Palco', 'Microfone', 'Cantor', 'Refrão', 'Concerto', 'Piano', 'Banda'] },
  { theme: 'Casa', words: ['Sofá', 'Cama', 'Janela', 'Chave', 'Telhado', 'Escada', 'Porta', 'Varanda', 'Garagem'] },
];
