// F&D — dados dos prompts (fonte única de verdade do conteúdo).
// Módulo PURO (sem efeitos) partilhado por:
//   - server/prisma/seed.js        (semeia a BD)
//   - server/src/repo.js           (repositório em memória, pré-BD)
// Assim o seed e o jogo nunca divergem.
// Cada prompt: [texto, intensidade] ou [texto, intensidade, { buddy?, duration? }].
//   buddy    → dispara a escolha de um "buddy" (bebe junto).
//   duration → regra que dura N jogadas (aviso persistente no ecrã).
//   tag      → pack temático ('aniversario' | 'despedida' | 'reencontro'). Sem tag
//              = serve qualquer ocasião (os packs são aditivos, não exclusivos).
// No tipo `isto_ou_aquilo`, o texto traz as DUAS opções separadas por "||".

export const GAME_TYPES = [
  {
    key: 'boca_calada',
    label: 'Boca Calada',
    prompts: [
      ['Fica sério durante 60s enquanto o grupo tenta fazer-te rir.', 'leve'],
      ['Não podes falar até ser a tua próxima vez. Falas = perdes vida.', 'leve'],
      ['Aguenta 30s a olhar nos olhos do jogador à tua direita sem rir.', 'leve'],
      ['Só podes responder por gestos até ao fim da ronda.', 'leve'],
      ['Mantém a cara séria enquanto o grupo conta a piada mais má que souber.', 'leve'],
      ['Fica calado e imita a expressão de quem estiver a falar contigo.', 'leve'],
      ['Aguenta sem sorrir enquanto todos dizem o teu nome em tom ridículo.', 'leve'],
      ['Não podes dizer "sim" nem "não" durante duas rondas.', 'leve'],
      ['Fica sério enquanto o grupo faz sons de animais à tua volta.', 'leve'],
      ['Mantém a boca fechada durante 45s enquanto te fazem cócegas com o olhar.', 'leve'],
      ['Aguenta sem rir enquanto alguém te elogia exageradamente.', 'leve'],
      ['Fica sério enquanto o grupo reencena o teu momento mais embaraçoso.', 'picante'],
      ['Não podes rir enquanto contam a história mais constrangedora sobre ti.', 'picante'],
      ['Aguenta sério enquanto o teu crush do grupo (se houver) te faz olhinhos.', 'picante'],
      ['Fica calado enquanto o grupo vota se és bom ou mau a beijar.', 'picante'],
      ['Mantém a pose enquanto alguém imita como ficas depois de uns copos.', 'picante'],
      ['Não podes reagir enquanto leem em voz alta a tua última mensagem enviada.', 'picante'],
      ['Fica sério enquanto o grupo descreve o teu tipo ideal.', 'picante'],
      ['Aguenta sem rir enquanto fazem uma imitação tua a paquerar.', 'picante'],
      ['Não podes falar enquanto respondes por gestos "o que farias numa primeira noite".', 'picante'],
      ['Mantém a cara séria enquanto o grupo adivinha o teu segredo mais picante.', 'picante'],
      ['Fica calado enquanto dois jogadores discutem quem gosta mais de ti.', 'picante'],
      ['Mantém a cara séria enquanto o grupo diz em voz alta o teu "tipo" na cama.', 'hardcore'],
      ['Aguenta sem reagir enquanto leem a tua conversa mais picante do telemóvel.', 'hardcore'],
      ['Fica sério enquanto o grupo vota quem levarias para casa esta noite.', 'hardcore'],
      ['Não podes rir enquanto alguém recria o teu pior fora da noite.', 'hardcore'],
      ['Mantém a pose enquanto descrevem o teu momento mais +18 conhecido.', 'hardcore'],
      ['Fica calado enquanto o grupo adivinha a tua fantasia mais secreta.', 'hardcore'],
      ['Fica calado enquanto cada um diz, à vez, uma verdade dura sobre ti.', 'caos'],
      ['Mantém a cara séria enquanto o grupo revela o que já disseram sobre ti nas costas.', 'caos'],
      ['Aguenta sem reagir enquanto dizem quem desta mesa aturam menos — e porquê.', 'caos'],
      ['Não podes falar enquanto expõem a tua maior falha de caráter (segundo o grupo).', 'caos'],
      ['Fica sério enquanto contam a última vez que ficaste mal na fita à frente deles.', 'caos'],
      ['Mantém a pose enquanto o grupo decide se és de confiança ou não.', 'caos'],
      ['Aguenta sem reagir enquanto o grupo adivinha quantas pessoas já beijaste.', 'hardcore'],
      ['Fica sério enquanto leem em voz alta os nomes das tuas últimas cinco conversas.', 'hardcore'],
      ['Não podes falar enquanto o grupo decide qual foi a tua pior escolha amorosa.', 'hardcore'],
      ['Mantém a cara séria enquanto imitam a tua voz a paquerar alguém.', 'hardcore'],
      ['Fica calado enquanto dizem, à vez, o que fariam contigo num encontro.', 'hardcore'],
      ['Aguenta sem reagir enquanto apostam quanto durou a tua relação mais curta.', 'hardcore'],
      ['Fica calado enquanto o grupo diz o que nunca te disse na cara.', 'caos'],
      ['Aguenta sem responder enquanto discutem se tinhas razão naquela discussão.', 'caos'],
      ['Mantém a pose enquanto votam quem aqui te conhece mesmo — e quem só finge.', 'caos'],
      ['Não podes falar enquanto contam a versão DELES da vossa última zanga.', 'caos'],
      ['Fica sério enquanto dizem o que mudariam em ti se pudessem.', 'caos'],
      ['Aguenta calado enquanto o grupo diz o que espera de ti e nunca pediu.', 'caos'],
      ['Fica sério enquanto o grupo tenta adivinhar em que estás a pensar.', 'leve'],
      ['Aguenta sem rir enquanto alguém conta a tua história mais contada de sempre.', 'picante'],
    ],
  },
  {
    key: 'desafio',
    label: 'Desafio',
    prompts: [
      ['Faz a tua melhor imitação de outro jogador; se ninguém adivinhar, bebes.', 'leve'],
      ['Fala com sotaque estrangeiro até à tua próxima vez.', 'leve'],
      ['Liga a um contacto aleatório e canta-lhe os parabéns.', 'leve'],
      ['Dança 20 segundos sem música.', 'leve'],
      ['Deixa o jogador à tua esquerda publicar um emoji no teu status.', 'leve'],
      ['Faz 10 flexões ou bebes dois copos.', 'leve'],
      ['Fala só a rimar durante a próxima ronda.', 'leve'],
      ['Imita um animal até alguém adivinhar qual é.', 'leve'],
      ['Deixa o grupo escolher-te uma nova alcunha para o resto do jogo.', 'leve'],
      ['Conta uma anedota; se ninguém rir, bebes.', 'leve'],
      ['Faz uma pose de ginásio e mantém-na 30s.', 'leve'],
      ['Envia "estava só a pensar em ti 😊" à terceira conversa do teu WhatsApp.', 'picante'],
      ['Mostra a última foto da tua galeria (sem escolher).', 'picante'],
      ['Deixa o grupo ler a tua última mensagem enviada em voz alta.', 'picante'],
      ['Descreve o teu pior encontro em três frases.', 'picante'],
      ['Deixa o jogador à tua direita escrever um story teu por 15s.', 'picante'],
      ['Troca uma peça de roupa com o jogador ao teu lado.', 'picante'],
      ['Faz uma serenata improvisada a quem o grupo escolher.', 'picante'],
      ['Confessa qual foi a maior mentira que disseste neste grupo.', 'picante'],
      ['Deixa o grupo ver quantas conversas tens fixadas — sem abrir.', 'picante'],
      ['Recria o teu melhor movimento de dança "de fim de noite".', 'picante'],
      ['Manda uma nota de voz a cantar para o último contacto com quem falaste.', 'picante'],
      ['Liga a um ex e diz "ainda penso em ti" durante 10s — ou bebes 3.', 'hardcore'],
      ['Mostra a última foto que enviaste a alguém depois da meia-noite.', 'hardcore'],
      ['Deixa o grupo ler a tua conversa mais recente, sem apagar nada.', 'hardcore'],
      ['Diz o nome de alguém no grupo com quem terias uma aventura — ou bebes 4.', 'hardcore'],
      ['Descreve o teu momento mais +18 em três palavras.', 'hardcore'],
      ['Deixa o jogador à tua direita publicar um story teu à escolha dele.', 'hardcore'],
      ['Qual foi a maior mentira que contaste a alguém desta mesa? Confessa ou bebes 3.', 'caos'],
      ['Diz qual das pessoas aqui já te irritou a sério — e porquê. Ou bebes 4.', 'caos'],
      ['Confessa a última vez que falaste de alguém desta mesa nas costas.', 'caos'],
      ['Ordena as pessoas da mesa de quem confias mais para quem confias menos, em voz alta.', 'caos'],
      ['Diz a coisa que mudarias em cada pessoa à tua esquerda e à tua direita.', 'caos'],
      ['Revela um crush passado ou presente por alguém desta mesa — ou bebes 5.', 'caos'],
      // Buddy (escolhes alguém que bebe contigo)
      ['Escolhe um buddy: até à tua próxima vez, sempre que bebes, ele/ela bebe também.', 'leve', { buddy: true }],
      ['Escolhe o teu buddy da desgraça — bebem sempre em dobro, juntos, nesta ronda.', 'picante', { buddy: true }],
      // Regras com duração (aviso persistente no ecrã)
      ['Até às próximas 2 jogadas, tens de rimar sempre que falas — senão bebes.', 'leve', { duration: 2 }],
      ['Nas próximas 2 jogadas, só podes falar na terceira pessoa — senão bebes.', 'leve', { duration: 2 }],
      ['Nas próximas 3 jogadas, acaba cada frase com "meu capitão" — senão bebes.', 'leve', { duration: 3 }],
      ['Até às próximas 2 jogadas, não podes dizer "sim" nem "não" — senão bebes.', 'picante', { duration: 2 }],
      ['Lê em voz alta a última mensagem que enviaste depois das 2 da manhã — ou bebes 4.', 'hardcore'],
      ['Deixa o grupo escolher alguém das tuas conversas e manda-lhe "olá" agora.', 'hardcore'],
      ['Diz em voz alta quantas pessoas já beijaste — ou bebes 4.', 'hardcore'],
      ['Mostra ao grupo a foto de perfil do teu último crush — ou bebes 5.', 'hardcore'],
      ['Deixa quem está à tua esquerda escolher um emoji e envia-o à tua última conversa.', 'hardcore'],
      ['Conta o teu maior arrependimento de uma noite de festa, sem cortes — ou bebes 4.', 'hardcore'],
      ['Diz qual das pessoas desta mesa te desiludiu mais — ou bebes 5.', 'caos'],
      ['Conta algo que sabes sobre alguém aqui e que mais ninguém sabe — ou bebes 5.', 'caos'],
      ['Escolhe com quem desta mesa viverias e com quem nunca — e explica porquê.', 'caos'],
      ['Diz o que pensaste da primeira vez que viste cada pessoa à tua direita.', 'caos'],
      ['Admite a última vez que mentiste a alguém desta mesa — ou bebes 4.', 'caos'],
      ['Diz quem aqui achas que te trocaria por outro grupo de amigos — ou bebes 4.', 'caos'],
    ],
  },
  {
    // Isto ou Aquilo — dilema com DUAS opções (texto = "A||B"); o da vez escolhe uma.
    key: 'isto_ou_aquilo',
    label: 'Isto ou Aquilo',
    prompts: [
      ['Fazer o pino durante 10s||Imitar um animal até alguém adivinhar', 'leve'],
      ['Cantar o refrão da tua música favorita||Dançar 15s sem música', 'leve'],
      ['Contar uma anedota; se ninguém rir, bebes 2||Beber 2 golos já', 'leve'],
      ['Falar com sotaque até à tua próxima vez||Trocar de lugar com alguém', 'leve'],
      ['Deixar o grupo escolher-te uma alcunha||Fazer 10 flexões', 'leve'],
      ['Beber 3 golos||Mostrar a última foto da galeria (sem escolher)', 'picante'],
      ['Mandar "estava a pensar em ti 😊" à 3.ª conversa||Beber 4 golos', 'picante'],
      ['Deixar o grupo ler a tua última mensagem enviada||Beber 3 golos', 'picante'],
      ['Beber 2 golos e fazer o pino||Mandar mensagem a alguém com quem já te relacionaste', 'hardcore'],
      ['Revelar o teu crush do grupo||Beber 5 golos', 'hardcore'],
      ['Ligar a um ex e falar 10s||Beber 5 golos', 'hardcore'],
      ['Dizer o que achas mesmo de quem está à tua frente||Beber 5 golos', 'caos'],
      ['Confessar a maior mentira que disseste a alguém da mesa||Beber 4 golos', 'caos'],
      ['Falar só a cantar durante uma ronda||Beber 2 golos', 'leve'],
      ['Fazer 15 agachamentos||Deixar o grupo ver o teu ecrã principal', 'leve'],
      ['Imitar o anfitrião durante 30s||Beber 2 golos', 'leve'],
      ['Contar a tua pior desculpa de sempre||Fazer uma pose ridícula durante 30s', 'leve'],
      ['Trocar de lugar com quem está à tua frente||Beber 2 golos', 'leve'],
      ['Falar em voz de desenho animado até à tua vez||Beber 3 golos', 'leve'],
      ['Deixar alguém escolher o teu próximo copo||Fazer uma imitação à escolha do grupo', 'leve'],
      ['Mostrar a tua última pesquisa no telemóvel||Beber 4 golos', 'picante'],
      ['Dizer a maior diferença de idade que já houve num encontro teu||Beber 3 golos', 'picante'],
      ['Ler em voz alta a tua última mensagem recebida||Beber 4 golos', 'picante'],
      ['Deixar o grupo ver as tuas capturas de ecrã||Beber 5 golos', 'picante'],
      ['Contar o teu pior fora numa paquera||Beber 3 golos', 'picante'],
      ['Dizer quantas conversas apagaste este mês||Beber 3 golos', 'picante'],
      ['Fazer uma cantada a quem está à tua direita||Beber 4 golos', 'picante'],
      ['Dizer a última pessoa cujo perfil espreitaste||Beber 4 golos', 'picante'],
      ['Contar o teu encontro mais desastroso||Deixar o grupo escrever-te um story', 'picante'],
      ['Ler a tua conversa mais recente em voz alta||Beber 5 golos', 'hardcore'],
      ['Dizer quem desta mesa acharias atraente||Beber 5 golos', 'hardcore'],
      ['Mostrar quem está no topo das tuas conversas||Beber 4 golos', 'hardcore'],
      ['Contar o teu maior segredo de uma noite||Beber 5 golos', 'hardcore'],
      ['Ligar ao teu último crush e falar 15s||Beber 6 golos', 'hardcore'],
      ['Dizer em quantas relações já pensaste em desistir||Beber 4 golos', 'hardcore'],
      ['Mostrar a última foto que tiraste a ti próprio/a||Beber 4 golos', 'hardcore'],
      ['Contar onde foste mais longe do que devias||Beber 5 golos', 'hardcore'],
      ['Deixar o grupo ver as tuas fotos favoritas||Beber 6 golos', 'hardcore'],
      ['Dizer quem aqui perdeu a tua confiança||Beber 5 golos', 'caos'],
      ['Contar o que já disseste de alguém desta mesa pelas costas||Beber 5 golos', 'caos'],
      ['Ordenar a mesa do amigo mais leal ao menos leal||Beber 6 golos', 'caos'],
      ['Dizer a quem desta mesa nunca emprestarias dinheiro||Beber 4 golos', 'caos'],
      ['Revelar uma discussão vossa que ainda não está resolvida||Beber 5 golos', 'caos'],
      ['Dizer quem aqui te irrita mais quando estão em grupo||Beber 5 golos', 'caos'],
      ['Dizer o que pensas mesmo da última decisão de quem está à tua frente||Beber 5 golos', 'caos'],
      ['Admitir se já duvidaste de uma amizade desta mesa||Beber 4 golos', 'caos'],
      ['Dizer quem daqui convidarias para o teu casamento — e quem não||Beber 6 golos', 'caos'],
      ['Contar o que mais te custou perdoar a alguém aqui||Beber 5 golos', 'caos'],
    ],
  },
  {
    key: 'intrigas',
    label: 'Intrigas',
    prompts: [
      ['Quem é mais capaz de adormecer numa festa? O grupo vota.', 'leve'],
      ['Quem chega sempre atrasado? Votem.', 'leve'],
      ['Quem tem o pior gosto musical? Votação.', 'leve'],
      ['Quem é mais provável de perder o telemóvel esta noite?', 'leve'],
      ['Quem fala mais alto quando bebe?', 'leve'],
      ['Quem seria o pior a guardar um segredo?', 'leve'],
      ['Quem gasta mais tempo ao espelho?', 'leve'],
      ['Quem é mais capaz de comer o que sobra no prato dos outros?', 'leve'],
      ['Quem seria o primeiro a fugir num filme de terror?', 'leve'],
      ['Quem tem sempre a desculpa mais criativa para faltar?', 'leve'],
      ['Quem é o mais dramático do grupo?', 'leve'],
      ['Quem é mais provável de mandar mensagem ao ex a meio da noite?', 'picante'],
      ['Quem já teve a maior queda por alguém deste grupo?', 'picante'],
      ['Quem é mais capaz de beijar um desconhecido numa saída?', 'picante'],
      ['Quem tem mais probabilidade de ter um crush secreto agora mesmo?', 'picante'],
      ['Quem seria o mais atrevido num jogo de verdade ou consequência?', 'picante'],
      ['Quem já flirtou para não pagar a conta?', 'picante'],
      ['Quem é mais provável de se apaixonar em férias?', 'picante'],
      ['Quem tem o histórico de encontros mais caótico?', 'picante'],
      ['Quem seria o primeiro a dizer "eu amo-te" cedo demais?', 'picante'],
      ['Quem é mais capaz de dar o número falso a alguém?', 'picante'],
      ['Quem tem a maior probabilidade de acabar a noite a dançar em cima da mesa?', 'picante'],
      ['Quem do grupo já teve a noite mais louca? Votem.', 'hardcore'],
      ['Quem é mais capaz de dar uns beijos a um desconhecido hoje?', 'hardcore'],
      ['Quem tem o histórico mais caótico de mensagens a horas tardias?', 'hardcore'],
      ['Quem seria o mais atrevido debaixo dos lençóis?', 'hardcore'],
      ['Quem já ficou (ou quase) com alguém deste grupo?', 'hardcore'],
      ['Quem é mais provável de acabar a noite acompanhado/a?', 'hardcore'],
      ['Quem nesta mesa é mais falso? O grupo decide.', 'caos'],
      ['Quem já falou mal de mais gente aqui presente?', 'caos'],
      ['Em quem confias menos para guardar um segredo teu?', 'caos'],
      ['Quem é mais provável de andar a namoriscar alguém do grupo às escondidas?', 'caos'],
      ['Quem seria o primeiro a trair o grupo por interesse próprio?', 'caos'],
      ['Quem aqui já gostou de alguém do grupo e nunca admitiu?', 'caos'],
      ['Quem já ficou com mais gente numa só noite?', 'hardcore'],
      ['Quem tem as conversas mais atrevidas guardadas no telemóvel?', 'hardcore'],
      ['Quem é mais capaz de sair daqui com alguém que acabou de conhecer?', 'hardcore'],
      ['Quem já disse "não conto a ninguém" e contou na mesma?', 'hardcore'],
      ['Quem tem a maior diferença entre o que mostra e o que faz?', 'hardcore'],
      ['Quem seria mais capaz de aceitar um convite duvidoso esta noite?', 'hardcore'],
      ['Quem desta mesa desaparece mais quando alguém precisa?', 'caos'],
      ['Quem já magoou mais alguém deste grupo sem nunca pedir desculpa?', 'caos'],
      ['Quem tem mais dois pesos e duas medidas com os amigos?', 'caos'],
      ['Quem seria o primeiro a contar um segredo vosso a alguém de fora?', 'caos'],
      ['Quem é mais capaz de ficar calado a ver um amigo levar a culpa?', 'caos'],
      ['Quem aqui julga mais os outros em silêncio?', 'caos'],
      ['Quem é mais capaz de se perder a caminho de um sítio conhecido?', 'leve'],
      ['Quem é mais provável de deixar uma conversa a meio para ir falar com outra pessoa?', 'picante'],
    ],
  },
  {
    key: 'segredos',
    label: 'Segredos Anónimos',
    prompts: [
      ['Submete um segredo sobre a tua infância. O grupo adivinha de quem é.', 'leve'],
      ['Confessa anonimamente um medo estranho que tenhas.', 'leve'],
      ['Partilha a coisa mais infantil que ainda fazes.', 'leve'],
      ['Escreve um talento escondido que ninguém aqui conhece.', 'leve'],
      ['Confessa um hábito esquisito que tens quando estás sozinho/a.', 'leve'],
      ['Partilha a compra mais inútil que já fizeste.', 'leve'],
      ['Escreve algo por que já choraste a ver um filme.', 'leve'],
      ['Confessa uma mentira inofensiva que dizes com frequência.', 'leve'],
      ['Partilha o prato que finges gostar mas odeias.', 'leve'],
      ['Escreve a coisa mais embaraçosa que tens no histórico de pesquisa.', 'leve'],
      ['Confessa uma manha que usas para faltar a compromissos.', 'leve'],
      ['Partilha um segredo sobre a tua vida amorosa. O grupo adivinha de quem é.', 'picante'],
      ['Confessa anonimamente o teu maior arrependimento romântico.', 'picante'],
      ['Escreve o sítio mais inusitado onde já deste um beijo.', 'picante'],
      ['Partilha algo que nunca contaste a ninguém deste grupo.', 'picante'],
      ['Confessa se já tiveste um crush em alguém presente (sem dizer quem).', 'picante'],
      ['Escreve a mensagem mais atrevida que já enviaste.', 'picante'],
      ['Partilha o encontro mais louco que já tiveste.', 'picante'],
      ['Confessa uma paixoneta secreta por alguém famoso improvável.', 'picante'],
      ['Escreve algo de que te arrependes de ter feito numa festa.', 'picante'],
      ['Partilha a desculpa mais dramática que já deste para acabar um encontro.', 'picante'],
      ['Confessa o segredo que levarias para o túmulo... até agora.', 'picante'],
      ['Confessa anonimamente a tua fantasia mais inconfessável.', 'hardcore'],
      ['Escreve o sítio mais arriscado onde já foste longe demais.', 'hardcore'],
      ['Partilha o segredo +18 que nunca contaste a ninguém.', 'hardcore'],
      ['Confessa se já tiveste algo com alguém presente — sem dizer quem.', 'hardcore'],
      ['Escreve a coisa mais atrevida que já fizeste sóbrio/a.', 'hardcore'],
      ['Partilha o teu maior arrependimento de uma noite de festa.', 'hardcore'],
      ['Confessa (anónimo) a maior mentira que já disseste a alguém desta mesa.', 'caos'],
      ['Escreve o que realmente sentiste da última vez que discutiste com alguém aqui.', 'caos'],
      ['Confessa se já perdeste o respeito por alguém do grupo — sem dizer quem.', 'caos'],
      ['Partilha a coisa mais dramática que já fizeste por causa de alguém desta mesa.', 'caos'],
      ['Escreve um arrependimento que tens com alguém presente.', 'caos'],
      ['Confessa se alguma vez fingiste gostar de alguém do grupo.', 'caos'],
      ['Escreve a coisa mais atrevida que já te pediram — e se aceitaste.', 'hardcore'],
      ['Confessa o pensamento que tiveste sobre alguém e nunca admitiste.', 'hardcore'],
      ['Partilha a maior mentira que já contaste para safar uma noite.', 'hardcore'],
      ['Escreve o que farias se ninguém deste grupo viesse a saber.', 'hardcore'],
      ['Confessa o que fizeste que mudaria a opinião do grupo sobre ti.', 'hardcore'],
      ['Partilha o momento em que estiveste mais perto de estragar tudo.', 'hardcore'],
      ['Escreve o que sentes mesmo por uma pessoa desta mesa — sem dizer quem.', 'caos'],
      ['Confessa uma vez em que ficaste aliviado/a com o azar de alguém aqui.', 'caos'],
      ['Partilha o que nunca perdoaste a alguém deste grupo.', 'caos'],
      ['Escreve o que dirias a alguém desta mesa se não houvesse consequências.', 'caos'],
      ['Confessa se alguma vez te afastaste do grupo de propósito.', 'caos'],
      ['Partilha a razão verdadeira por que faltaste àquela vez.', 'caos'],
      ['Escreve o elogio que gostavas de ouvir e nunca ouves.', 'leve'],
      ['Confessa a coisa mais atrevida que já escreveste e não enviaste.', 'picante'],
    ],
  },
  {
    // Piramide (Desconfia) — jogo dirigido por MECÂNICA, não por prompts de texto.
    // As cartas e a pirâmide são geradas no motor (game.js); não há banco de prompts.
    // Fica em GAME_TYPES só para entrar na roda (repo.getGameTypes) e no seed (0 prompts).
    key: 'piramide',
    label: 'Piramide',
    prompts: [],
  },
  {
    // Jogo do Vasco (Impostor) — também dirigido por MECÂNICA. O conteúdo são
    // QUADROS de palavras (VASCO_BOARDS abaixo), não prompts de texto. Fica aqui
    // só para entrar na roda e no seed (0 prompts).
    key: 'vasco',
    label: 'Jogo do Vasco',
    prompts: [],
  },
  {
    // Categoria Relâmpago — o texto do prompt É a categoria. Todos dizem itens em
    // voz alta (fora da app) enquanto o cronómetro corre; quem travar bebe.
    key: 'categoria_relampago',
    label: 'Categoria Relâmpago',
    prompts: [
      ['Marcas de cerveja', 'leve'],
      ['Equipas da Primeira Liga', 'leve'],
      ['Pratos portugueses', 'leve'],
      ['Cidades de Portugal', 'leve'],
      ['Marcas de carros', 'leve'],
      ['Animais com quatro patas', 'leve'],
      ['Coisas que há numa cozinha', 'leve'],
      ['Cantores portugueses', 'leve'],
      ['Doces de pastelaria', 'leve'],
      ['Programas de televisão portugueses', 'leve'],
      ['Peças de roupa', 'leve'],
      ['Desculpas para chegar atrasado', 'leve'],
      ['Bebidas que se pedem num bar', 'picante'],
      ['Sítios inusitados para dar um beijo', 'picante'],
      ['Coisas que se dizem numa paquera', 'picante'],
      ['Apps de encontros', 'picante'],
      ['Desculpas para não ir a um segundo encontro', 'picante'],
      ['Ressacas: o que se faz no dia seguinte', 'picante'],
      ['Partes do corpo', 'hardcore'],
      ['Coisas que nunca dirias aos teus pais', 'hardcore'],
      ['Palavrões que já disseste hoje', 'hardcore'],
      ['Sítios onde já foste longe demais', 'hardcore'],
      ['Motivos para acabar uma relação', 'caos'],
      ['Defeitos que toda a gente tem', 'caos'],
      ['Coisas que se dizem quando se fala mal de alguém', 'caos'],
      ['Mentiras que já contaste a este grupo', 'caos'],
      ['Sítios onde já dormiste que não são a tua cama', 'hardcore'],
      ['Coisas que já disseste para acabar uma discussão', 'hardcore'],
      ['Desculpas para sair de casa de alguém de manhã', 'hardcore'],
      ['Coisas que se encontram no quarto de alguém', 'hardcore'],
      ['Motivos para bloquear uma pessoa', 'hardcore'],
      ['Coisas que nunca porias num perfil de encontros', 'hardcore'],
      ['Frases que só se dizem às 4 da manhã', 'hardcore'],
      ['Coisas que já fizeste e não contaste a ninguém', 'hardcore'],
      ['Razões para deixar de falar com um amigo', 'caos'],
      ['Coisas que se dizem numa discussão e não se pensam', 'caos'],
      ['Segredos que um grupo de amigos costuma ter', 'caos'],
      ['Motivos para sair de um grupo de WhatsApp', 'caos'],
      ['Coisas que se fazem por inveja', 'caos'],
      ['Desculpas que já não enganam ninguém', 'caos'],
      ['Sinais de que uma amizade acabou', 'caos'],
      ['Coisas que nunca dirias à frente de toda a gente', 'caos'],
      ['Coisas que se dizem antes de uma asneira', 'picante'],
      ['Desculpas para chegar tarde a casa', 'picante'],
      ['Sítios para um primeiro encontro', 'picante'],
      ['Coisas que se fazem para impressionar alguém', 'picante'],
      ['Frases típicas de quem já bebeu demais', 'picante'],
      ['Razões para não responder a uma mensagem', 'picante'],
    ],
  },
  {
    // Mímica/Desenho Rápido — o texto do prompt É a palavra a mimar/desenhar.
    // A palavra vai PRIVADA para quem está à vez (canal `mimica_word`).
    key: 'mimica',
    label: 'Mímica',
    prompts: [
      ['Ressaca', 'leve'],
      ['Karaoke', 'leve'],
      ['Selfie', 'leve'],
      ['Guarda-redes', 'leve'],
      ['Churrasco', 'leve'],
      ['Autocarro cheio', 'leve'],
      ['Bolo de aniversário', 'leve'],
      ['Praia ao vento', 'leve'],
      ['Dentista', 'leve'],
      ['Vaca', 'leve'],
      ['Trânsito na ponte', 'leve'],
      ['Mergulho', 'leve'],
      ['Cair na rua', 'leve'],
      ['Ganhar a lotaria', 'leve'],
      ['Primeiro encontro', 'picante'],
      ['Dança sensual', 'picante'],
      ['Beijo à francesa', 'picante'],
      ['Bêbado a cantar', 'picante'],
      ['Story embaraçoso', 'picante'],
      ['Cantada foleira', 'picante'],
      ['Discussão de casal', 'picante'],
      ['Fugir do encontro', 'picante'],
      ['Pedido de casamento falhado', 'hardcore'],
      ['Apanhado pelos pais', 'hardcore'],
      ['Mensagem para o ex às 3 da manhã', 'hardcore'],
      ['Strip improvisado', 'hardcore'],
      ['Traição descoberta', 'caos'],
      ['Falar mal de alguém pelas costas', 'caos'],
      ['Drama de grupo no WhatsApp', 'caos'],
      ['Bloquear alguém nas redes', 'caos'],
      ['Sair às escondidas de manhã', 'hardcore'],
      ['Esconder o telemóvel à pressa', 'hardcore'],
      ['Apanhar o ex com outra pessoa', 'hardcore'],
      ['Ressaca no trabalho', 'hardcore'],
      ['Dançar em cima da mesa', 'hardcore'],
      ['Fingir que adora a prenda', 'hardcore'],
      ['Beijo às escuras', 'hardcore'],
      ['Ser apanhado a mentir', 'hardcore'],
      ['Discussão no grupo de amigos', 'caos'],
      ['Espalhar um boato', 'caos'],
      ['Fingir que está tudo bem', 'caos'],
      ['Apanhar alguém a falar de ti', 'caos'],
      ['Pedir desculpa a contragosto', 'caos'],
      ['Amizade a acabar', 'caos'],
      ['Ler a mensagem e não responder', 'caos'],
      ['Escolher entre dois amigos', 'caos'],
      ['Selfie que não sai bem', 'picante'],
      ['Encontro às cegas', 'picante'],
      ['Mandar mensagem à pessoa errada', 'picante'],
      ['Fingir que não viu a pessoa na rua', 'picante'],
    ],
  },
  {
    // Roleta Russa de Perguntas — pergunta embaraçosa; podes passar, mas o preço
    // sobe a cada passe (1, 2, 3 golos) até responderes ou estourares o máximo.
    key: 'roleta_russa',
    label: 'Roleta Russa',
    prompts: [
      ['Qual foi a maior vergonha que já passaste em público?', 'leve'],
      ['Qual é a coisa mais infantil que ainda fazes?', 'leve'],
      ['Qual é a mentira mais parva que já contaste?', 'leve'],
      ['Qual é o teu maior medo ridículo?', 'leve'],
      ['O que tens no histórico de pesquisa que não mostrarias?', 'leve'],
      ['Qual foi a pior prenda que já deste a alguém?', 'leve'],
      ['Qual é o hábito mais nojento que tens quando ninguém vê?', 'leve'],
      ['Qual foi a última vez que choraste — e porquê?', 'leve'],
      ['Quem foi o teu pior beijo e porquê?', 'picante'],
      ['Qual foi o encontro mais desastroso da tua vida?', 'picante'],
      ['Já enviaste mensagem à pessoa errada? O que dizia?', 'picante'],
      ['Qual é a coisa mais atrevida que já fizeste sóbrio/a?', 'picante'],
      ['Já ficaste com alguém e te arrependeste na hora?', 'picante'],
      ['Qual é o teu maior arrependimento romântico?', 'picante'],
      ['Já stalkeaste alguém a sério nas redes? Quem?', 'picante'],
      ['Quantas pessoas desta mesa já achaste atraentes?', 'picante'],
      ['Qual é a tua fantasia mais inconfessável?', 'hardcore'],
      ['Qual foi o sítio mais arriscado onde já foste longe demais?', 'hardcore'],
      ['Já tiveste alguma coisa com alguém presente?', 'hardcore'],
      ['Qual foi a tua noite mais louca de sempre — sem cortes?', 'hardcore'],
      ['O que farias por mil euros que nunca admitirias aqui?', 'hardcore'],
      ['Qual é a maior mentira que já contaste a alguém desta mesa?', 'caos'],
      ['De quem desta mesa já falaste mal — e o que disseste?', 'caos'],
      ['Em quem aqui confias menos e porquê?', 'caos'],
      ['Já perdeste o respeito por alguém deste grupo? Porquê?', 'caos'],
      ['Que pessoa desta mesa cortarias da tua vida sem pensar?', 'caos'],
      ['Qual foi a coisa mais atrevida que já te pediram?', 'hardcore'],
      ['Quantas pessoas já beijaste nesta cidade?', 'hardcore'],
      ['Qual foi a maior loucura que fizeste por atração?', 'hardcore'],
      ['Já fingiste sentir algo que não sentias? Quando?', 'hardcore'],
      ['Qual é o teu maior segredo de uma noite de festa?', 'hardcore'],
      ['Já saíste com alguém só por vaidade? Conta.', 'hardcore'],
      ['O que tens no telemóvel agora que não querias que ninguém visse?', 'hardcore'],
      ['Qual foi a última vez que magoaste alguém desta mesa?', 'caos'],
      ['Que amizade aqui já esteve quase a acabar por tua causa?', 'caos'],
      ['O que é que nunca perdoaste a alguém deste grupo?', 'caos'],
      ['Se pudesses apagar uma noite com esta gente, qual era?', 'caos'],
      ['Que verdade sobre ti é que este grupo não aguentaria?', 'caos'],
      ['Já ficaste calado/a a ver alguém aqui ser injusto? Quando?', 'caos'],
      ['Que pessoa desta mesa te desiludiu mais este ano?', 'caos'],
      ['Qual é a coisa mais parva por que já discutiste?', 'leve'],
      ['Qual é o teu maior talento inútil?', 'leve'],
      ['Qual foi a última vez que te fizeste de parvo/a de propósito?', 'leve'],
      ['O que é que ninguém aqui adivinharia sobre ti?', 'leve'],
      ['Qual foi a mensagem mais embaraçosa que já enviaste sem querer?', 'picante'],
      ['O que farias num encontro se soubesses que não havia segundo?', 'picante'],
      ['Qual é a desculpa que mais usas para não sair de casa?', 'picante'],
      ['Já mudaste de opinião sobre alguém depois de uma noite? Conta.', 'picante'],
    ],
  },
  {
    // Duelo 1v1 — mecânica pura: a roda sorteia adversário e mini-duelo simbólico
    // (DUELO_GAMES abaixo). Sem banco de prompts (fica só para entrar na roda).
    key: 'duelo',
    label: 'Duelo 1v1',
    prompts: [],
  },
  {
    // Eu Nunca — TODOS respondem ao mesmo tempo ("já" / "nunca"). Quem já fez, bebe.
    // O texto do prompt é a frase depois de "Eu nunca…".
    key: 'eu_nunca',
    label: 'Eu Nunca',
    prompts: [
      ['fui apanhado/a a mentir por uma pessoa desta mesa.', 'leve'],
      ['cantei no karaoke completamente sóbrio/a.', 'leve'],
      ['fingi que sabia uma música só para não ficar mal.', 'leve'],
      ['dormi numa festa antes da meia-noite.', 'leve'],
      ['fui a um concerto de um artista que detesto.', 'leve'],
      ['chorei a ver um filme de animação.', 'leve'],
      ['dei um like sem querer numa foto de 2015.', 'leve'],
      ['inventei uma doença para faltar ao trabalho ou às aulas.', 'leve'],
      ['perdi o telemóvel numa noite e apareceu no dia seguinte.', 'leve'],
      ['comi a última fatia sem perguntar a ninguém.', 'leve'],
      ['fui de casa com a roupa do avesso o dia inteiro.', 'leve'],
      ['guardei um número no telemóvel com um nome falso.', 'picante'],
      ['enviei mensagem a um ex depois da meia-noite.', 'picante'],
      ['fingi uma chamada para fugir de uma conversa.', 'picante'],
      ['beijei alguém de quem não sabia o nome.', 'picante'],
      ['fui a um encontro só pela comida.', 'picante'],
      ['stalkei o novo par de um ex durante mais de meia hora.', 'picante'],
      ['tive um crush por alguém desta mesa.', 'picante'],
      ['menti sobre onde estava para não ir a um plano.', 'picante'],
      ['saí de uma festa sem me despedir de ninguém.', 'picante'],
      ['fiquei com duas pessoas na mesma noite.', 'hardcore'],
      ['dei um beijo em alguém comprometido.', 'hardcore'],
      ['fiz algo de que me arrependo mesmo a sério nesta cidade.', 'hardcore'],
      ['menti sobre o meu passado a alguém importante.', 'hardcore'],
      ['fui longe demais num sítio público.', 'hardcore'],
      ['bebi tanto que não me lembro de como cheguei a casa.', 'hardcore'],
      ['falei mal de alguém desta mesa nas últimas semanas.', 'caos'],
      ['guardei um segredo que estraga a noite de alguém aqui.', 'caos'],
      ['já pensei em cortar relações com alguém deste grupo.', 'caos'],
      ['li mensagens no telemóvel de alguém sem autorização.', 'caos'],
      ['menti a este grupo sobre uma coisa importante.', 'caos'],
      ['fui a uma festa de anos sem levar prenda.', 'leve', { tag: 'aniversario' }],
      ['esqueci-me do aniversário de alguém muito próximo.', 'leve', { tag: 'aniversario' }],
      ['fiz asneira numa despedida de solteiro/a.', 'picante', { tag: 'despedida' }],
      ['perdi alguém de vista numa despedida e só apareceu de manhã.', 'picante', { tag: 'despedida' }],
      ['deixei de falar com alguém deste grupo durante meses.', 'picante', { tag: 'reencontro' }],
      ['mudei completamente de vida sem contar a ninguém aqui.', 'leve', { tag: 'reencontro' }],
      ['saí de manhã de casa de alguém sem dizer nada.', 'hardcore'],
      ['menti sobre com quem estava naquela noite.', 'hardcore'],
      ['fiquei com alguém que já tinha ficado com um amigo meu.', 'hardcore'],
      ['apaguei mensagens antes de alguém pegar no meu telemóvel.', 'hardcore'],
      ['inventei uma história inteira para impressionar alguém.', 'hardcore'],
      ['fiz algo numa festa de que nunca falei com ninguém.', 'hardcore'],
      ['contei um segredo de alguém desta mesa a outra pessoa.', 'caos'],
      ['fingi apoiar alguém aqui a pensar exatamente o contrário.', 'caos'],
      ['fiquei aliviado/a quando um plano de alguém deste grupo correu mal.', 'caos'],
      ['evitei uma pessoa desta mesa de propósito durante semanas.', 'caos'],
      ['julguei alguém deste grupo por uma escolha que fez.', 'caos'],
      ['guardei ressentimento de alguém aqui durante mais de um ano.', 'caos'],
      ['deixei alguém deste grupo levar a culpa por uma coisa minha.', 'caos'],
    ],
  },
  {
    // Quem é mais provável — TODOS votam num jogador. O mais votado bebe.
    key: 'mais_provavel',
    label: 'Mais Provável',
    prompts: [
      ['adormecer primeiro esta noite', 'leve'],
      ['perder o telemóvel esta semana', 'leve'],
      ['chegar atrasado a tudo', 'leve'],
      ['cantar no karaoke sem ninguém pedir', 'leve'],
      ['ficar rico sem trabalhar', 'leve'],
      ['dar a volta ao mundo sozinho/a', 'leve'],
      ['comer o jantar de outra pessoa', 'leve'],
      ['ter uma coleção secreta estranha', 'leve'],
      ['discutir com um empregado de mesa', 'leve'],
      ['emigrar de um dia para o outro', 'leve'],
      ['chorar com um anúncio de Natal', 'leve'],
      ['acabar a noite a comer no chão da cozinha', 'picante'],
      ['mandar mensagem ao ex esta noite', 'picante'],
      ['ficar com alguém à frente de toda a gente', 'picante'],
      ['ter uma história que ninguém aqui conhece', 'picante'],
      ['apaixonar-se em 24 horas', 'picante'],
      ['fugir de um encontro a meio', 'picante'],
      ['dar o número a um desconhecido esta noite', 'picante'],
      ['acordar num sítio que não reconhece', 'hardcore'],
      ['fazer o maior disparate da noite', 'hardcore'],
      ['ter mais segredos do que admite', 'hardcore'],
      ['ficar com alguém desta mesa', 'hardcore'],
      ['fazer algo que dava escândalo se se soubesse', 'hardcore'],
      ['falar mal de alguém deste grupo pelas costas', 'caos'],
      ['trair a confiança de um amigo', 'caos'],
      ['começar uma discussão sem razão nenhuma', 'caos'],
      ['guardar rancor durante anos', 'caos'],
      ['ser o motivo do próximo drama do grupo', 'caos'],
      ['fazer o discurso mais embaraçoso da festa', 'leve', { tag: 'aniversario' }],
      ['acabar de fato de banho na despedida', 'picante', { tag: 'despedida' }],
      ['ser o primeiro a chorar no reencontro', 'leve', { tag: 'reencontro' }],
      ['sair de uma festa com alguém que acabou de conhecer', 'hardcore'],
      ['ter uma conversa apagada por apagar', 'hardcore'],
      ['esconder uma relação do grupo', 'hardcore'],
      ['fazer esta noite algo de que se arrepende amanhã', 'hardcore'],
      ['ter muito mais histórias do que já contou', 'hardcore'],
      ['dizer que sim a um convite duvidoso', 'hardcore'],
      ['acordar sem saber onde deixou o casaco', 'hardcore'],
      ['contar um segredo do grupo a alguém de fora', 'caos'],
      ['desaparecer quando alguém precisa mesmo', 'caos'],
      ['começar um boato sem querer', 'caos'],
      ['ficar calado perante uma injustiça', 'caos'],
      ['guardar rancor por uma coisa pequena', 'caos'],
      ['escolher outro grupo de amigos se pudesse', 'caos'],
      ['ser o motivo do próximo mal-entendido', 'caos'],
      ['deixar a conversa em visto durante três dias', 'picante'],
      ['aceitar um plano só para não ficar mal', 'picante'],
      ['contar a mesma história a toda a gente da festa', 'picante'],
      ['acabar a noite a fazer planos que nunca vai cumprir', 'picante'],
    ],
  },
  {
    // Termómetro — cada um escolhe 0–10 em SEGREDO e revela-se tudo ao mesmo
    // tempo. Os extremos (mais alto e mais baixo) bebem.
    key: 'termometro',
    label: 'Termómetro',
    prompts: [
      ['Quão bêbado/a estás agora? (0 = sóbrio, 10 = não sabes o teu nome)', 'leve'],
      ['Quão bom/boa és a cantar? (0 = terrível, 10 = profissional)', 'leve'],
      ['Quão bem dormiste esta semana?', 'leve'],
      ['Quão organizada está a tua casa neste momento?', 'leve'],
      ['Quão competitivo/a és a jogar?', 'leve'],
      ['Quão bem cozinhas?', 'leve'],
      ['Quão pontual és de verdade?', 'leve'],
      ['Quão feliz estás com a tua vida hoje?', 'leve'],
      ['Quão bem aguentas as bebidas?', 'picante'],
      ['Quão ciumento/a és numa relação?', 'picante'],
      ['Quão bem beijas (segundo os outros)?', 'picante'],
      ['Quão arriscado/a és numa noite de festa?', 'picante'],
      ['Quão dependente és do telemóvel?', 'picante'],
      ['Quão perto estás de mandar mensagem a quem não devias?', 'picante'],
      ['Quão longe já foste por alguém de quem gostavas?', 'hardcore'],
      ['Quão escandaloso seria o teu histórico de pesquisa?', 'hardcore'],
      ['Quão disponível estás para uma loucura hoje?', 'hardcore'],
      ['Quão bem esconderias uma traição?', 'hardcore'],
      ['Quão honesto/a és com este grupo?', 'caos'],
      ['Quão fácil seria cortares com alguém desta mesa?', 'caos'],
      ['Quão bem julgas as pessoas em segredo?', 'caos'],
      ['Quão fiável és quando alguém precisa mesmo de ti?', 'caos'],
      ['Quão memorável tem sido esta festa até agora?', 'leve', { tag: 'aniversario' }],
      ['Quão descontrolada vai acabar esta despedida?', 'picante', { tag: 'despedida' }],
      ['Quão diferente estás desde a última vez que se viram?', 'leve', { tag: 'reencontro' }],
      ['Quão longe irias por alguém que acabaste de conhecer?', 'hardcore'],
      ['Quão escandalosas são as conversas que já apagaste?', 'hardcore'],
      ['Quão perto estás de fazer uma loucura esta noite?', 'hardcore'],
      ['Quão diferente és quando ninguém deste grupo está a ver?', 'hardcore'],
      ['Quão bem esconderias um segredo grande?', 'hardcore'],
      ['Quão à vontade estarias a passar o telemóvel desbloqueado?', 'hardcore'],
      ['Quão arrependido/a estás da tua última decisão amorosa?', 'hardcore'],
      ['Quão impulsivo/a ficas depois da meia-noite?', 'hardcore'],
      ['Quão sincero/a foste com este grupo este ano?', 'caos'],
      ['Quão perto estiveste de cortar com alguém desta mesa?', 'caos'],
      ['Quão justo/a achas que este grupo é contigo?', 'caos'],
      ['Quão substituível te sentes neste grupo?', 'caos'],
      ['Quão bem achas que te conhecem aqui?', 'caos'],
      ['Quão difícil te seria pedir desculpa a alguém desta mesa?', 'caos'],
      ['Quão magoado/a ainda estás com uma coisa antiga?', 'caos'],
      ['Quão dependente és da opinião desta mesa?', 'caos'],
      ['Quão bem guardas uma surpresa?', 'leve'],
      ['Quão teimoso/a és quando tens razão?', 'leve'],
      ['Quão à vontade ficas a dançar em público?', 'picante'],
      ['Quão rápido perdoas uma pessoa de quem gostas?', 'picante'],
      ['Quão sincero/a costumas ser num primeiro encontro?', 'picante'],
      ['Quão saudoso/a ficas de relações antigas?', 'picante'],
      ['Quão fácil é convencer-te a ficar mais uma hora?', 'picante'],
    ],
  },
  {
    // Desenha e Adivinha — a palavra vai PRIVADA a quem desenha (canal
    // 'desenho_word'); os traços vão por um canal próprio ('draw_stroke'), não
    // pelo room_state. O texto do prompt É a palavra.
    key: 'desenho',
    label: 'Desenha',
    prompts: [
      ['Ressaca', 'leve'],
      ['Pastel de nata', 'leve'],
      ['Elétrico de Lisboa', 'leve'],
      ['Selfie de grupo', 'leve'],
      ['Festa de aniversário', 'leve'],
      ['Cão a fugir', 'leve'],
      ['Sardinha assada', 'leve'],
      ['Guarda-chuva partido', 'leve'],
      ['Karaoke', 'leve'],
      ['Praia cheia', 'leve'],
      ['Fila do supermercado', 'leve'],
      ['Bicicleta sem roda', 'leve'],
      ['Cair da cadeira', 'leve'],
      ['Ganhar a lotaria', 'leve'],
      ['Casamento à pressa', 'picante'],
      ['Primeiro encontro desastroso', 'picante'],
      ['Beijo interrompido', 'picante'],
      ['Fugir pela janela', 'picante'],
      ['Mensagem às 3 da manhã', 'picante'],
      ['Dança sensual', 'picante'],
      ['Apanhado pelos sogros', 'picante'],
      ['Ex a aparecer na festa', 'picante'],
      ['Regresso a casa de manhã', 'hardcore'],
      ['Roupa espalhada pelo chão', 'hardcore'],
      ['Chamada perdida do patrão', 'hardcore'],
      ['Discussão de casal na rua', 'hardcore'],
      ['Traição descoberta', 'caos'],
      ['Grupo de WhatsApp em chamas', 'caos'],
      ['Bloquear alguém nas redes', 'caos'],
      ['Amizade desfeita', 'caos'],
      ['Sair às escondidas', 'hardcore'],
      ['Telemóvel a tocar às 3 da manhã', 'hardcore'],
      ['Encontro às escuras', 'hardcore'],
      ['Roupa no chão do quarto', 'hardcore'],
      ['Fuga pela janela', 'hardcore'],
      ['Ressaca no trabalho', 'hardcore'],
      ['Dançar em cima do balcão', 'hardcore'],
      ['Beijo apanhado numa foto', 'hardcore'],
      ['Grupo a discutir', 'caos'],
      ['Mensagem lida sem resposta', 'caos'],
      ['Boato a espalhar-se', 'caos'],
      ['Amigo a virar as costas', 'caos'],
      ['Pedido de desculpa mal dado', 'caos'],
      ['Segredo a escapar', 'caos'],
      ['Escolher entre dois amigos', 'caos'],
      ['Festa que acabou mal', 'caos'],
      ['Corrida para apanhar o metro', 'picante'],
      ['Selfie que corre mal', 'picante'],
      ['Jantar entre dois que não se falam', 'picante'],
      ['Telemóvel sem bateria', 'picante'],
    ],
  },
  {
    // Quem Disse Isto — mecânica pura: usa as PERGUNTAS escritas na preparação e
    // o grupo adivinha quem a escreveu. Conteúdo grátis e sempre pessoal.
    key: 'quem_disse',
    label: 'Quem Disse',
    prompts: [],
  },
  {
    // Cascata — mecânica pura: todos começam a beber ao mesmo tempo e só podes
    // parar depois de quem está antes de ti na ordem. O último bebe mais.
    key: 'cascata',
    label: 'Cascata',
    prompts: [],
  },
  {
    // Reação (Primeiro a Carregar) — mecânica pura: conta decrescente com atraso
    // aleatório; o último a carregar bebe. Também é duelo no Torneio e casa no Tabuleiro.
    key: 'reacao',
    label: 'Reação',
    prompts: [],
  },

  // ----- Tipos "hardcore" (camada 3) ------------------------------------------
  // Estes seis sobem a aposta em CONSEQUÊNCIA, não em volume: o que muda é quem
  // decide, quanto custa decidir mal, e o que sobra depois de a ronda acabar.

  {
    // Bomba-Relógio — o texto do prompt é o TEMA que se vai dizendo enquanto a
    // bomba anda à volta. Sem intensidade forte de propósito: o que aperta aqui
    // é o pavio, não a pergunta.
    key: 'bomba',
    label: 'Bomba-Relógio',
    prompts: [
      ['Marcas de cerveja', 'leve'],
      ['Coisas que se levam para a praia', 'leve'],
      ['Cantores portugueses', 'leve'],
      ['Programas de televisão', 'leve'],
      ['Coisas que há numa mochila', 'leve'],
      ['Desportos olímpicos', 'leve'],
      ['Marcas de telemóvel', 'leve'],
      ['Cidades europeias', 'leve'],
      ['Doces de pastelaria', 'leve'],
      ['Coisas que se dizem numa despedida', 'leve'],
      ['Desculpas para faltar ao trabalho', 'picante'],
      ['Sítios improváveis para dar um beijo', 'picante'],
      ['Mentiras que já contámos aos pais', 'picante'],
      ['Coisas que se fazem quando ninguém está a ver', 'picante'],
      ['Razões para bloquear alguém', 'picante'],
      ['Coisas que só se dizem depois de três copos', 'hardcore'],
      ['Motivos reais para acabar uma relação', 'hardcore'],
      ['Coisas de que já te arrependeste no dia seguinte', 'hardcore'],
      ['Segredos que este grupo já não guarda bem', 'caos'],
      ['Assuntos que ninguém devia trazer à mesa', 'caos'],
    ],
  },
  {
    // Leilão — o texto é o DESAFIO que ninguém quer fazer. Tem de ser sempre uma
    // coisa concreta e executável ali, senão não há por que licitar.
    key: 'leilao',
    label: 'Leilão',
    prompts: [
      ['Faz uma imitação de alguém desta mesa até adivinharem quem é.', 'leve'],
      ['Canta o refrão da última música que ouviste, de pé.', 'leve'],
      ['Fala como um narrador de futebol durante a próxima ronda inteira.', 'leve'],
      ['Deixa a pessoa à tua direita escolher-te um penteado novo agora.', 'leve'],
      ['Conta uma história tua de dois minutos sem dizer a letra "a".', 'leve'],
      ['Faz uma dança de trinta segundos sem música.', 'leve'],
      ['Manda mensagem à terceira pessoa da tua lista a dizer que tens saudades.', 'picante'],
      ['Lê em voz alta a última mensagem que enviaste a alguém.', 'picante'],
      ['Deixa a mesa ver a tua galeria de fotos durante dez segundos.', 'picante'],
      ['Liga a alguém e canta-lhe os parabéns sem explicar porquê.', 'picante'],
      ['Conta o momento mais embaraçoso do último ano, com detalhes.', 'picante'],
      ['Deixa alguém desta mesa publicar uma story no teu perfil.', 'hardcore'],
      ['Diz o que pensas mesmo sobre a pessoa à tua esquerda, na cara dela.', 'hardcore'],
      ['Lê em voz alta a tua última conversa com o teu/tua ex.', 'hardcore'],
      ['Responde com sinceridade a qualquer pergunta que a mesa quiser fazer.', 'caos'],
      ['Entrega o telemóvel desbloqueado a alguém desta mesa por uma ronda.', 'caos'],
    ],
  },
  {
    // Sincronia — a resposta é sempre um JOGADOR, por isso as perguntas têm de
    // apontar para dentro da mesa. "Quem…", nunca "o quê".
    key: 'sincronia',
    label: 'Sincronia',
    prompts: [
      ['Quem desta mesa chega sempre atrasado?', 'leve'],
      ['Quem é o primeiro a querer ir para casa?', 'leve'],
      ['Quem come sempre a comida dos outros?', 'leve'],
      ['Quem fala mais alto quando bebe?', 'leve'],
      ['Quem é o mais dramático do grupo?', 'leve'],
      ['Quem sobrevivia mais tempo sozinho numa ilha?', 'leve'],
      ['Quem é que nunca lê as mensagens do grupo?', 'leve'],
      ['Quem tem sempre uma desculpa pronta?', 'leve'],
      ['Quem desta mesa mente melhor?', 'picante'],
      ['Quem já ficou com alguém e não contou a ninguém?', 'picante'],
      ['Quem é mais capaz de stalkar um ex às três da manhã?', 'picante'],
      ['Quem é que a mesa toda acha que está apaixonado e não admite?', 'picante'],
      ['Quem mandava a mensagem errada à pessoa errada?', 'picante'],
      ['Quem desta mesa guarda o pior segredo dos outros?', 'hardcore'],
      ['Quem é que já falou mal de alguém que está aqui sentado?', 'hardcore'],
      ['Quem trairia primeiro o grupo por um bom motivo?', 'caos'],
    ],
  },
  {
    // Detetor de Mentiras — perguntas que dão MESMO para mentir. Uma pergunta de
    // resposta óbvia ou verificável não serve: a mesa tem de ficar em dúvida.
    key: 'detetor',
    label: 'Detetor',
    prompts: [
      ['Já fugiste de uma conta num restaurante?', 'leve'],
      ['Já fingiste estar doente para faltar a um plano com alguém desta mesa?', 'leve'],
      ['Já dormiste num sítio muito estranho? Conta qual.', 'leve'],
      ['Já perdeste alguma coisa muito cara de alguém e não contaste?', 'leve'],
      ['Já cantaste em público sozinho?', 'leve'],
      ['Já chumbaste a alguma coisa e disseste que tinhas passado?', 'leve'],
      ['Já ficaste com alguém que este grupo conhece?', 'picante'],
      ['Já leste as mensagens de alguém sem essa pessoa saber?', 'picante'],
      ['Já disseste "eu amo-te" sem sentir?', 'picante'],
      ['Já saíste de casa de alguém sem dizer adeus?', 'picante'],
      ['Já inventaste uma história inteira só para impressionar alguém?', 'picante'],
      ['Já traíste a confiança de alguém que está nesta mesa?', 'hardcore'],
      ['Já tiveste um crush por alguém deste grupo?', 'hardcore'],
      ['Já mentiste sobre uma coisa importante a quem estava contigo?', 'hardcore'],
      ['Já fizeste alguma coisa esta noite de que ninguém aqui faz ideia?', 'caos'],
      ['Há alguma coisa que este grupo pensa de ti que é mentira?', 'caos'],
    ],
  },
  {
    // Julgamento — a acusação. Escrita SEM nome: o réu é quem estiver à vez, e o
    // texto tem de encaixar em qualquer pessoa da mesa.
    key: 'julgamento',
    label: 'Julgamento',
    prompts: [
      ['É acusado de ser quem mais estraga os planos do grupo.', 'leve'],
      ['É acusado de nunca pagar a sua parte da conta à primeira.', 'leve'],
      ['É acusado de chegar sempre atrasado e nunca pedir desculpa.', 'leve'],
      ['É acusado de falar demasiado sobre si próprio.', 'leve'],
      ['É acusado de ser o pior a escolher música.', 'leve'],
      ['É acusado de desaparecer das conversas de grupo quando lhe convém.', 'leve'],
      ['É acusado de dar conselhos que nunca segue.', 'leve'],
      ['É acusado de contar segredos dos outros como se fossem histórias.', 'picante'],
      ['É acusado de ser o mais falso a elogiar.', 'picante'],
      ['É acusado de trocar os amigos por quem lhe interessa no momento.', 'picante'],
      ['É acusado de já ter mentido a alguém desta mesa este mês.', 'picante'],
      ['É acusado de fingir estar bem para não ter de falar do assunto.', 'hardcore'],
      ['É acusado de ser quem mais julga os outros à socapa.', 'hardcore'],
      ['É acusado de ter magoado alguém desta mesa e nunca ter admitido.', 'caos'],
    ],
  },
  {
    // Contrato — o pacto. Tem de ser cumprível ao longo de várias rondas e
    // verificável por quem está à mesa (a fiscalização é da mesa, não da app).
    key: 'contrato',
    label: 'Contrato',
    prompts: [
      ['Bebem sempre ao mesmo tempo: se um bebe, o outro acompanha.', 'leve'],
      ['Não podem dizer o nome um do outro — só apelidos inventados.', 'leve'],
      ['Falam sempre no plural, como se fossem uma pessoa só.', 'leve'],
      ['Têm de estar de acordo em todas as votações da mesa.', 'leve'],
      ['Sempre que um for desafiado, o outro tem de o defender em voz alta.', 'leve'],
      ['Não podem falar um com o outro diretamente — só através de terceiros.', 'leve'],
      ['Um só pode beber depois de pedir licença ao outro.', 'leve'],
      ['Respondem sempre às perguntas do outro com sinceridade total.', 'picante'],
      ['Cada um tem de elogiar o outro, a sério, antes de cada ronda.', 'picante'],
      ['Se um recusar um desafio, o outro tem de o fazer por ele.', 'picante'],
      ['Partilham tudo o que a mesa perguntar a qualquer um dos dois.', 'hardcore'],
      ['Ficam responsáveis um pelo outro: o castigo de um é dos dois.', 'hardcore'],
    ],
  },
];

// Mini-duelos simbólicos do Duelo 1v1 — resolvem-se FORA da app (presencial); a
// app só sorteia qual é e regista quem ganhou.
export const DUELO_GAMES = [
  {
    key: 'par_impar',
    emoji: '✌️',
    label: 'Par ou Ímpar',
    desc: 'Contagem até três e cada um mostra os dedos de uma mão. Combinem quem fica com par e quem fica com ímpar.',
  },
  {
    key: 'cara_coroa',
    emoji: '🪙',
    label: 'Cara ou Coroa',
    desc: 'A moeda é lançada aqui na app. Quem lançou o duelo escolhe a face; se sair a outra, perde.',
  },
  {
    key: 'braco_ferro',
    emoji: '💪',
    label: 'Braço de Ferro',
    desc: 'Cotovelos na mesa, mãos dadas. À melhor de uma — sem cotoveladas.',
  },
];

// Quadros do Jogo do Vasco: cada quadro tem um tema e 9 palavras (grelha 3×3).
// O grupo recebe uma das palavras como secreta; o(s) Vasco(s) não a sabem e têm
// de a adivinhar pelas pistas. Palavras neutras (sem intensidade).
export const VASCO_BOARDS = [
  { theme: 'Praia', words: ['Mar', 'Areia', 'Sol', 'Toalha', 'Chapéu', 'Onda', 'Barco', 'Concha', 'Bronzeado'] },
  { theme: 'Cozinha', words: ['Faca', 'Panela', 'Forno', 'Sal', 'Colher', 'Prato', 'Fogão', 'Azeite', 'Frigorífico'] },
  { theme: 'Festa', words: ['Música', 'Balões', 'Bolo', 'Copos', 'Dança', 'Prenda', 'Convite', 'Vela', 'Confetti'] },
  { theme: 'Futebol', words: ['Golo', 'Árbitro', 'Bola', 'Relvado', 'Adepto', 'Penálti', 'Camisola', 'Estádio', 'Baliza'] },
  { theme: 'Cinema', words: ['Pipocas', 'Ecrã', 'Bilhete', 'Realizador', 'Trailer', 'Cadeira', 'Legenda', 'Estreia', 'Ator'] },
  { theme: 'Viagem', words: ['Mala', 'Avião', 'Passaporte', 'Hotel', 'Mapa', 'Comboio', 'Roteiro', 'Fronteira', 'Câmara'] },
  { theme: 'Escola', words: ['Caderno', 'Professor', 'Exame', 'Recreio', 'Mochila', 'Quadro', 'Nota', 'Caneta', 'Intervalo'] },
  { theme: 'Animais', words: ['Cão', 'Gato', 'Leão', 'Elefante', 'Cobra', 'Águia', 'Golfinho', 'Coelho', 'Tubarão'] },
  { theme: 'Corpo', words: ['Cabeça', 'Mão', 'Joelho', 'Cotovelo', 'Ombro', 'Nariz', 'Tornozelo', 'Dedo', 'Costas'] },
  { theme: 'Natal', words: ['Presente', 'Pinheiro', 'Presépio', 'Rena', 'Neve', 'Bacalhau', 'Pai Natal', 'Estrela', 'Meia'] },
  { theme: 'Música', words: ['Guitarra', 'Bateria', 'Palco', 'Microfone', 'Cantor', 'Refrão', 'Concerto', 'Piano', 'Banda'] },
  { theme: 'Casa', words: ['Sofá', 'Cama', 'Janela', 'Chave', 'Telhado', 'Escada', 'Porta', 'Varanda', 'Garagem'] },
];
